package com.example.restaurant.pojo;
// Generated 11-Jun-2021, 11:37:55 am by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Menuitems generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "menuitems", catalog = "restaurant")
public class Menuitems implements java.io.Serializable {

	private Integer id;
	private String itemName;
	private Integer price;

	public Menuitems() {
	}

	public Menuitems(@JsonProperty("itemname") String itemName,@JsonProperty("price") Integer price) {
		this.itemName = itemName;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "item_name", length = 40)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
