package com.example.restaurant.pojo;
// Generated 11-Jun-2021, 11:37:55 am by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Userdata generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "userdata", catalog = "restaurant")
public class Userdata implements java.io.Serializable {

	private String emailid;
	private String uname;
	private String upassword;
	private int token;
	public Userdata() {
	}
	
	public Userdata(String emailid, String uname, String upassword, int token) {
		this.emailid = emailid;
		this.uname = uname;
		this.upassword = upassword;
		this.token = token;
	}

	public Userdata(@JsonProperty("emailid")  String emailid, String uname,@JsonProperty("password")  String upassword) {
		this.emailid = emailid;
		this.uname = uname;
		this.upassword = upassword;
	}
	public Userdata(String emailid, String upassword) {
		this.emailid = emailid;
		this.upassword = upassword;
	}
	
	

	@Id

	@Column(name = "emailid", unique = true, nullable = false, length = 100)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "uname", nullable = false, length = 20)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "upassword", nullable = false, length = 100)
	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	public int getToken() {
		return token;
	}

	public void setToken(int token) {
		this.token = token;
	}

}
